jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode gsheet credentials
        run: |
          echo "${{ secrets.GSHEET_CREDS_B64 }}" | base64 -d > gsheet-creds.json

      - name: Run scraper
        run: python your_script.py
